export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_ADDRESSES = 'FETCH_ADDRESSES';
export const REMOVE_ADDRESSES = 'REMOVE_ADDRESSES';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const FETCH_EVALS_TYPES = 'FETCH_EVALS_TYPES';
export const FETCH_EVALS = 'FETCH_EVALS';
export const EVALS_ERROR = 'EVALS_ERROR';

export const LOADING_QUIZES = 'LOADING_QUIZES';
export const FECTH_QUIZES = 'FECTH_QUIZES';
export const FETCH_SELECTED_QUIZ = 'FETCH_SELECTED_QUIZ';
export const QUIZ_ERROR = 'QUIZ_ERROR';

export const LOADING_EVAL_QUESTION = 'LOADING_EVAL_QUESTION';
export const FETCH_EVAL_QUESTION = 'FETCH_EVAL_QUESTION';
export const EVAL_QUESTION_ERROR = 'EVAL_QUESTION_ERROR';
